ASK_NAME, ASK_CONTACT, ASK_SERVICE, ASK_DAY, ASK_PREF_TIME, ASK_COMMENT, CONFIRM = range(7)

SERVICES = ["Massage", "Cut", "Manicure", "Pedicure"]

TOKEN = "PASTE_YOUR_TOKEN"

ADMIN_IDS = ["PASTE YOUR ID AS A INTEGER"]

DB_PATH = "PASTE YOUR PATH TO DATABASE"
